### ISSUE TITLE
插件有兼容问题？

### ISSUE THREAD

**Issue by sy-records** [mengkunsoft/mk-letter-avatar#2]
使用`get_avatar()`获取的头像，`onerror`也存在。
![image](https://user-images.githubusercontent.com/33931153/56088271-6f3bf980-5eaf-11e9-97df-dd6e07a44180.png)
但是依旧输入默认图片

**Comment by sy-records** [comment]
嗯好吧，插件里判断有问题，导致替换失效。

默认头像是神秘人士或者空白的时候，默认还是存在图片链接的。

源代码地址：[mk-letter-avatar.php#L27](https://github.com/mengkunsoft/mk-letter-avatar/blob/master/mk-letter-avatar.php#L27)

**Comment by mengkunsoft** [comment]
感谢反馈！经查是头像链接被 html 转义后无法匹配引起的，已发布修复版本！
